apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: placeholder
  source:
    repoURL: https://github.com/DramisInfo/it-open-webui-workspace
    targetRevision: HEAD
    path: deploy/open-webui
  destination:
    server: https://kubernetes.default.svc
    namespace: placeholder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[].backendRefs[].group
        - .spec.rules[].backendRefs[].kind
        - .spec.rules[].backendRefs[].weight
        - .spec.rules[].matches
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
