apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: open-webui-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: openwebui
      owner: openwebui
